system:
  port: 8888
  node: 0
  db-type: mysql
database:
  path: 192.168.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: axg
  username: root
  password: "axg123456"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "error"
  log-zap: false
jwt:
  signing-key: jCyJhbGciOi7ruWCOt29eJIUzI
  expires-time: 30
zap:
  level: info
  format: console
  prefix: '[axg]'
  director: log
  link-name: latest_log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
